use_frameworks!

target 'gqbHttpEngine_Example' do
  pod 'gqbHttpEngine', :path => '../gqbaoHttpEngine.podspec'
  pod 'AFNetworking', '~> 3.2.0'

  target 'gqbHttpEngine_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end


