use_frameworks!

target 'gqbHttpEngine_Example' do
  pod 'gqbHttpEngine', :path => '../'

  target 'gqbHttpEngine_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
